<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_bulan_berdiri_juni</name>
   <tag></tag>
   <elementGuidId>d890a287-c2b2-4fdc-bb1d-0e6c807c59d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu-business_started_month&quot;]/div[3]/ul/li[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu-business_started_month&quot;]/div[3]/ul/li[6]</value>
   </webElementProperties>
</WebElementEntity>
