<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tanggal_pilih</name>
   <tag></tag>
   <elementGuidId>fbb2ec79-f453-4433-83e0-4547db363b55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[4]/div[1]/div/div/div/div/div[3]/div[3]/div[3]/div[2]/div/div/div[2]/div[2]/div[5]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[4]/div[1]/div/div/div/div/div[3]/div[3]/div[3]/div[2]/div/div/div[2]/div[2]/div[5]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
