<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_17_pengeluaran_untuk_biaya_tenaga_kerja_harian</name>
   <tag></tag>
   <elementGuidId>44bcd25f-b5f8-4ff4-8031-831221487106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;daily_labor_costs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;daily_labor_costs&quot;]</value>
   </webElementProperties>
</WebElementEntity>
