<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_8_pembayaran_sewa_dibayar_dimuka_atas_lahan_yang_digunakan</name>
   <tag></tag>
   <elementGuidId>426f303f-875d-474e-9770-8cd1605b9641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;prepaid_rent_payments&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;prepaid_rent_payments&quot;]</value>
   </webElementProperties>
</WebElementEntity>
