<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_3_harga_perolehan_bangunan</name>
   <tag></tag>
   <elementGuidId>7cf74b59-9331-4a91-a784-3cc4c999dbab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;building_acquisition_cost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;building_acquisition_cost&quot;]</value>
   </webElementProperties>
</WebElementEntity>
