<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_11_harga_perolehan_pembelian_mesin_baru</name>
   <tag></tag>
   <elementGuidId>0185d7aa-cdb4-4a6d-a2b2-9e7081e5d0b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;new_machine_cost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;new_machine_cost&quot;]</value>
   </webElementProperties>
</WebElementEntity>
