<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_10_retur_pembelian_persediaan_yang_rusak</name>
   <tag></tag>
   <elementGuidId>f9ff6999-dcfb-48e3-8c91-b8477b55f190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;purchase_return&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;purchase_return&quot;]</value>
   </webElementProperties>
</WebElementEntity>
