<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_14_menerima_pendapatan_jasa_otomotif_secara_tunai</name>
   <tag></tag>
   <elementGuidId>146788d3-974f-4e59-adb0-58b47557edf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;income_in_cash&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;income_in_cash&quot;]</value>
   </webElementProperties>
</WebElementEntity>
