<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_6_umur_aset_kendaraan</name>
   <tag></tag>
   <elementGuidId>86d800a4-5c4e-4b2c-84ec-f253f791c93e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;vehicle_economic_age&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;vehicle_economic_age&quot;]</value>
   </webElementProperties>
</WebElementEntity>
