<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_5_harga_perolehan_kendaraan</name>
   <tag></tag>
   <elementGuidId>04558556-2e1e-431d-9c68-a65ea80b445d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;vehicle_acquisition_cost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;vehicle_acquisition_cost&quot;]</value>
   </webElementProperties>
</WebElementEntity>
