<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_selanjutnya</name>
   <tag></tag>
   <elementGuidId>a15153f8-db4b-4a6e-9aeb-a5134f6eda6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[5]/div[2]/div/div[2]/div/div[2]/div[9]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[5]/div[2]/div/div[2]/div/div[2]/div[9]/button</value>
   </webElementProperties>
</WebElementEntity>
