<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_sifat_kepemilikan_swakelola</name>
   <tag></tag>
   <elementGuidId>786463b0-e807-499a-a922-681eb960a33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu-ownership&quot;]/div[3]/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu-ownership&quot;]/div[3]/ul/li[1]</value>
   </webElementProperties>
</WebElementEntity>
