<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_bidang_usaha_jasa</name>
   <tag></tag>
   <elementGuidId>e49a2ed7-9fad-4161-a2a9-b51588f2849e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu-business_field_id62&quot;]/div[3]/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu-business_field_id62&quot;]/div[3]/ul/li[1]</value>
   </webElementProperties>
</WebElementEntity>
