<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_jabatan_pengurus_owner</name>
   <tag></tag>
   <elementGuidId>d1ed804e-ad2e-4ef5-8053-97ac641aabac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu-position&quot;]/div[3]/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu-position&quot;]/div[3]/ul/li[1]</value>
   </webElementProperties>
</WebElementEntity>
