<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_unit_usaha_jasasewa</name>
   <tag></tag>
   <elementGuidId>2189ce8d-138e-4a49-a287-ba10032a481f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu-business_unit_id62&quot;]/div[3]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu-business_unit_id62&quot;]/div[3]/ul/li</value>
   </webElementProperties>
</WebElementEntity>
