<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soal_1.1</name>
   <tag></tag>
   <elementGuidId>90252c6e-ab95-4137-910d-000511840d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[1]/div/div/div[1]/div/div/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[1]/div/div/div[1]/div/div/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
