<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soal_7.6_input</name>
   <tag></tag>
   <elementGuidId>8048810b-4840-4d90-97df-9673e002fd6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[7]/div/div/div[6]/div/div/div/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[7]/div/div/div[6]/div/div/div/div/div/div[1]</value>
   </webElementProperties>
</WebElementEntity>
