<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soal_3_1_checkbox</name>
   <tag></tag>
   <elementGuidId>48381bf8-60b1-4378-9f51-a047e6fff5d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[3]/div/div/div[1]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[3]/div/div/div[1]/div/label</value>
   </webElementProperties>
</WebElementEntity>
