<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soal_5_radio</name>
   <tag></tag>
   <elementGuidId>267c7baf-c515-41e4-b9b9-9fef383774a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[5]/div/div/div[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[5]/div/div/div[3]/label</value>
   </webElementProperties>
</WebElementEntity>
