<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soal_7.1_input</name>
   <tag></tag>
   <elementGuidId>a58513f0-86c9-4143-ac34-575e39a77b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div[1]/div[2]/div/div[7]/div/div/div[1]/div/div/div/div/div/div[1]/div[1][count(. | //*[@class = concat('//*[@class=' , &quot;'&quot; , 'css-1uccc91-singleValue' , &quot;'&quot; , ']')]) = count(//*[@class = concat('//*[@class=' , &quot;'&quot; , 'css-1uccc91-singleValue' , &quot;'&quot; , ']')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[4]/div[2]/div[1]/div[2]/div/div[7]/div/div/div[1]/div/div/div/div/div/div[1]/div[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>//*[@class='css-1uccc91-singleValue']</value>
   </webElementProperties>
</WebElementEntity>
