<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_simpan_confirm</name>
   <tag></tag>
   <elementGuidId>26bdb246-abab-4e47-97b4-6d6944a05bdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[5]/div[2]/div/div[2]/div/div[8]/div/div/p/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[5]/div[2]/div/div[2]/div/div[8]/div/div/p/a[2]</value>
   </webElementProperties>
</WebElementEntity>
