<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_doticon</name>
   <tag></tag>
   <elementGuidId>ee042d6a-c6e5-415c-a6c0-9954e3db6788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[2]/div/div/div[2]/div/div[1]/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[2]/div/div/div[2]/div/div[1]/div[2]/div/i</value>
   </webElementProperties>
</WebElementEntity>
