<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_video_play</name>
   <tag></tag>
   <elementGuidId>d9eb6598-8a19-4a77-bbf5-c1f9d41f349a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[5]/div/div/div/div[1]/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[5]/div/div/div/div[1]/div/video</value>
   </webElementProperties>
</WebElementEntity>
