<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_video_1</name>
   <tag></tag>
   <elementGuidId>3bdc6595-f987-4ddd-ba7e-273efb45051a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[5]/div/div/div/div[2]/div[2]/div/div/div/div[2]/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[5]/div/div/div/div[2]/div[2]/div/div/div/div[2]/div[1]/div</value>
   </webElementProperties>
</WebElementEntity>
