<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pertanyaan_4</name>
   <tag></tag>
   <elementGuidId>152f7b8d-d34b-444e-ba1a-9aa5bfe493db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[5]/div[2]/div/div[2]/div/div[5]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[5]/div[2]/div/div[2]/div/div[5]/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
