<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pertanyaan_1</name>
   <tag></tag>
   <elementGuidId>ac07d7d3-5dbf-4441-b44b-4143dd26a58f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[5]/div[2]/div/div[2]/div/div[2]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[5]/div[2]/div/div[2]/div/div[2]/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
