<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_reversal</name>
   <tag></tag>
   <elementGuidId>1493c58b-0867-4f59-9068-6dd01dce8b88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[5]/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[5]/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/i</value>
   </webElementProperties>
</WebElementEntity>
