<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>soal_2_radio</name>
   <tag></tag>
   <elementGuidId>34939748-9424-4f0e-83f3-68bea52a0be9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[2]/div/div/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[2]/div[1]/div[2]/div/div[2]/div/div/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
