<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_lihat</name>
   <tag></tag>
   <elementGuidId>73e3ec40-9244-487b-bbfa-d8ca7866811a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[5]/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[5]/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/div/i</value>
   </webElementProperties>
</WebElementEntity>
