<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_lihat_halaman_perspektif_kehadiran_negara</name>
   <tag></tag>
   <elementGuidId>1cd8664c-99fd-4fdb-b11c-931574eef398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[4]/div[2]/div[1]/div[1]/div/ol/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[4]/div[2]/div[1]/div[1]/div/ol/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
